
USE NCAA;

DROP TABLE IF EXISTS general;
CREATE TABLE IF NOT EXISTS general (
	game_id VARCHAR(255),
    season VARCHAR(255),
    neutral_site VARCHAR(255),
    scheduled_date VARCHAR(255),
    gametime VARCHAR(255),
    tournament VARCHAR(255),
    tournament_type VARCHAR(255),
    tournament_round VARCHAR(255),
    tournament_game VARCHAR(255),
    player_id VARCHAR(255),
    last_name VARCHAR(255),
    first_name VARCHAR(255),
    full_name VARCHAR(255),
    abbr_name VARCHAR(255),
    status VARCHAR(10),
    jersey_number VARCHAR(255),
    height VARCHAR(255),
    weight VARCHAR(255),
    birthplace VARCHAR(255),
    birthplace_city VARCHAR(40),
    birthplace_state VARCHAR(40),
    birthplace_country VARCHAR(40),
    class VARCHAR(40),
    team_name VARCHAR(255),
    team_market VARCHAR(255),
    team_id VARCHAR(255),
    team_alias VARCHAR(20),
    conf_name VARCHAR(255),
    conf_alias VARCHAR(20),
    division_name VARCHAR(255),
    division_alias VARCHAR(20),
    league_name VARCHAR(255),
    home_team VARCHAR(255),
    active VARCHAR(255),
    played VARCHAR(255),
    starter VARCHAR(255),
    minutes VARCHAR(255),
    minutes_int64 VARCHAR(255),
    position VARCHAR(255),
    primary_position VARCHAR(255),
    field_goals_made VARCHAR(255),
    field_goals_att VARCHAR(255),
    field_goals_pct VARCHAR(255),
    three_points_made VARCHAR(255),
    three_points_att VARCHAR(255),
    three_points_pct VARCHAR(255),
    two_points_made VARCHAR(255),
    two_points_att VARCHAR(255),
    two_points_pct VARCHAR(255),
    blocked_att VARCHAR(255),
    free_throws_made VARCHAR(255),
    free_throws_att VARCHAR(255),
    free_throws_pct VARCHAR(255),
    offensive_rebounds VARCHAR(255),
    defensive_rebounds VARCHAR(255),
    rebounds VARCHAR(255),
    assits VARCHAR(255),
    turnovers VARCHAR(255),
    steals VARCHAR(255),
    blocks VARCHAR(255),
    assists_turnover_ratio VARCHAR(255),
    personal_fouls VARCHAR(255),
    tech_fouls VARCHAR(255),
    flagrant_fouls VARCHAR(255),
    points VARCHAR(255),
    sp_created VARCHAR(255)
);

LOAD DATA INFILE '/Users/cocomungai/Documents/Vanderbilt\ University/Year\ 3/3.3/CS\ 3265/Project/bq-results-20190418-173125-gs13sh8eyunf.csv'
INTO TABLE general
FIELDS TERMINATED BY ','
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 ROWS;